kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: home-lab
nodes:
- role: control-plane
  extraMounts:
    - hostPath: /home/cleversonc6/.volume_kind
      containerPath: /volume_host
- role: worker
- role: worker
