apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: cleversondeveloper/gitopsfc
  newTag: f542e4aef3f2129675096a50ed85233b3e91c1ad
